# Generated by Django 6.1.1 on 2026-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('groups', models.CharField(choices=[('C', 'C'), ('W', 'W'), ('S', 'S'), ('L', 'L'), ('Lab', 'Lab'), ('CompLab', 'CompLab')], max_length=100)),
            ],
        ),
    ]
