# Generated by Django 6.1.1 on 2026-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkstudent', '0002_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.CharField(choices=[('C', 'C'), ('W', 'W'), ('S', 'S'), ('L', 'L'), ('Lab', 'Lab'), ('CompLab', 'CompLab')], max_length=100)),
                ('section', models.CharField(blank=True, choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('C5', 'C5'), ('W1', 'W1'), ('W2', 'W2'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('Lek1', 'Lek1'), ('Lek2', 'Lek2'), ('Lek3', 'Lek3'), ('Lek4', 'Lek4'), ('Lek5', 'Lek5'), ('Lek6', 'Lek6'), ('Lek7', 'Lek7'), ('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('L5', 'L5'), ('L6', 'L6'), ('L7', 'L7'), ('L8', 'L8'), ('L9', 'L9'), ('L10', 'L10'), ('L11', 'L11'), ('L12', 'L12'), ('L13', 'L13'), ('L14', 'L14'), ('LK1', 'LK1'), ('LK2', 'LK2'), ('LK3', 'LK3'), ('LK4', 'LK4'), ('LK5', 'LK5'), ('LK6', 'LK6'), ('Lk7', 'Lk7'), ('LK8', 'LK8'), ('LK9', 'LK9')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_groups',
            field=models.ManyToManyField(blank=True, to='pkstudent.student_group'),
        ),
    ]
