# Generated by Django 6.0.4 on 2026-10-06 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkstudent', '0003_student_group_remove_student_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=250)),
                ('group_label', models.CharField(max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=250)),
                ('room', models.CharField(blank=True, max_length=100)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_min', models.PositiveIntegerField()),
                ('interval_weeks', models.PositiveSmallIntegerField(default=1)),
                ('excluded_dates', models.JSONField(default=list)),
                ('overrides', models.JSONField(default=dict)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('start_date', 'start_time', 'event_type'),
            },
        ),
    ]
